language: python
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8-dev
  - pypy3
install: pip install tox-travis coverage coveralls
script: tox
after_success:
  - coverage combine
  - coveralls
cache:
  pip: true
