
variables:
  PYTEST_ADDOPTS: "--junitxml=build/test-results/$(tox.env).xml -vv"

jobs:
- job: 'Test'
  pool:
    vmImage: "vs2017-win2016"
  strategy:
    matrix:
      py35:
        python.version: '3.5'
        tox.env: 'py35-azure'
      py36:
        python.version: '3.6'
        tox.env: 'py36-azure'
      py37:
        python.version: '3.7'
        tox.env: 'py37-azure'
      py38:
        python.version: '3.8'
        tox.env: 'py38-azure'
    maxParallel: 10

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip && python -m pip install tox
    displayName: 'Install tox'

  - bash: |
      python -m tox -e $(tox.env)
    displayName: 'Run tests'
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'build/test-results/$(tox.env).xml'
      testRunTitle: '$(tox.env)'
    condition: succeededOrFailed()
